# Generated by Django 5.1 on 2024-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=25, verbose_name='Title')),
                ('anons', models.CharField(default='Default Anons', max_length=100, verbose_name='Anons')),
                ('full_text', models.TextField(default='Default Full Text', verbose_name='Full Text')),
                ('date', models.DateTimeField(verbose_name='DateTime')),
            ],
        ),
    ]
